/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.flexdesktop.user.GraphicInterface;

import com.flexdesktop.user.Error.InfError;

import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;

import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.Timer;

/**
 *
 * @author Melvin
 */
public class getInformation extends javax.swing.JDialog {

    /**
     * Creates new form EditRoutes
     *
     * @param parent
     * @param modal
     */
    private final Point point = new Point(0, 0);

    private String[] direccion = {"Direcciones"};
    private String[] phone = {"Phone"};

    public List<Object[]> data2 = new ArrayList<Object[]>();
    static private getInformation self;
    private int accion = 0;
    private final int BORRAR = 1;
    private final int Ver = 0;
    private final int Actualizar = 2;
    private final int Beneficiario = 7;
    private final int getIdCliente = 8;
    private String ced;

    public getInformation(java.awt.Frame parent, boolean modal) {

        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);

        this.jTable_Dirreciones.setModel(new tableModelAddres(direccion,
                data2, true));

        //Agregar una fila por defecto en las tablas
        addRow(jTable_Dirreciones);

    }
    static getInformation getSelf(){
    if(self ==null){
        return new getInformation(null, true);
    }
    return self;
    }

    public void showDialog(String panel) {

        final Timer timer = new Timer(30, null);
        timer.setRepeats(true);
        timer.addActionListener(new ActionListener() {
            private float opacity = 0;

            @Override
            public void actionPerformed(ActionEvent e) {
                opacity += 0.15f;
                setOpacity(Math.min(opacity, 1));
                if (opacity >= 1) {
                    timer.stop();
                }
            }
        });
        setOpacity(0);
        timer.start();

        setVisiblePanel(panel);
        setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        ConsultarClt = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jRadioButtonBuscarCed = new javax.swing.JRadioButton();
        jRadioButtonBuscarCuenta = new javax.swing.JRadioButton();
        jRadioButtonNombre = new javax.swing.JRadioButton();
        jRadioButtonApellido = new javax.swing.JRadioButton();
        jFormattedTextFieldBuscarPor = new javax.swing.JFormattedTextField();
        jLabelBusquedaPor = new javax.swing.JLabel();
        jLabelCreateClt = new javax.swing.JLabel();
        jLabelCreateBeneficiario = new javax.swing.JLabel();
        jLabelCrear = new javax.swing.JLabel();
        VerClt = new javax.swing.JPanel();
        jButton14 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabelApellido = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabelCedula = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabelBorrarClt = new javax.swing.JLabel();
        registerClt = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jFormattedTextFieldEnterName = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jFormattedTextFieldEnterApellido = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jFormattedTextFieldEnterCedula = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_Dirreciones = new javax.swing.JTable();
        jButton9 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTablePhone = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(418, 578));
        setMinimumSize(new java.awt.Dimension(418, 578));
        setUndecorated(true);

        ConsultarClt.setBackground(new java.awt.Color(255, 255, 255));
        ConsultarClt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ConsultarClt.setMaximumSize(new java.awt.Dimension(418, 578));
        ConsultarClt.setMinimumSize(new java.awt.Dimension(418, 578));
        ConsultarClt.setPreferredSize(new java.awt.Dimension(418, 578));
        ConsultarClt.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                ConsultarCltMouseDragged(evt);
            }
        });
        ConsultarClt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ConsultarCltMousePressed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/flexdesktop/user/Images/hecho.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/flexdesktop/user/Images/atras.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Khmer UI", 0, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Buscar Por:");

        jLabel8.setFont(new java.awt.Font("Khmer UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Seleccionar Cliente");

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/flexdesktop/user/Images/close2.png"))); // NOI18N
        jButton6.setContentAreaFilled(false);
        jButton6.setFocusable(false);
        jButton6.setOpaque(true);
        jButton6.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/com/flexdesktop/user/Images/close2_roller.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonBuscarCed);
        jRadioButtonBuscarCed.setSelected(true);
        jRadioButtonBuscarCed.setText("Número de Cédula");
        jRadioButtonBuscarCed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonBuscarCedMouseClicked(evt);
            }
        });

        buttonGroup1.add(jRadioButtonBuscarCuenta);
        jRadioButtonBuscarCuenta.setText("Número de Cuenta");
        jRadioButtonBuscarCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonBuscarCuentaMouseClicked(evt);
            }
        });

        buttonGroup1.add(jRadioButtonNombre);
        jRadioButtonNombre.setText("Nombre");
        jRadioButtonNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonNombreMouseClicked(evt);
            }
        });

        buttonGroup1.add(jRadioButtonApellido);
        jRadioButtonApellido.setText("Apellido");
        jRadioButtonApellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonApellidoMouseClicked(evt);
            }
        });

        jLabelBusquedaPor.setText("Cédula:");

        jLabelCreateClt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/System/Images/Buttons/searchBtt.png"))); // NOI18N
        jLabelCreateClt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCreateCltMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelCreateCltMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelCreateCltMouseExited(evt);
            }
        });

        jLabelCreateBeneficiario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/System/Images/Buttons/addBtt.png"))); // NOI18N
        jLabelCreateBeneficiario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCreateBeneficiarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelCreateBeneficiarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelCreateBeneficiarioMouseExited(evt);
            }
        });

        jLabelCrear.setBackground(new java.awt.Color(255, 255, 255));
        jLabelCrear.setFont(new java.awt.Font("Khmer UI", 0, 13)); // NOI18N
        jLabelCrear.setForeground(new java.awt.Color(102, 102, 102));
        jLabelCrear.setText("Crear:");

        javax.swing.GroupLayout ConsultarCltLayout = new javax.swing.GroupLayout(ConsultarClt);
        ConsultarClt.setLayout(ConsultarCltLayout);
        ConsultarCltLayout.setHorizontalGroup(
            ConsultarCltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultarCltLayout.createSequentialGroup()
                .addGroup(ConsultarCltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ConsultarCltLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(ConsultarCltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(ConsultarCltLayout.createSequentialGroup()
                                .addGroup(ConsultarCltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jFormattedTextFieldBuscarPor, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelBusquedaPor, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(63, 63, 63))
                            .addGroup(ConsultarCltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(ConsultarCltLayout.createSequentialGroup()
                                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(247, 247, 247)
                                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(ConsultarCltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ConsultarCltLayout.createSequentialGroup()
                                        .addGap(60, 60, 60)
                                        .addGroup(ConsultarCltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jRadioButtonBuscarCed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jRadioButtonBuscarCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jRadioButtonNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jRadioButtonApellido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                    .addGroup(ConsultarCltLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabelCreateBeneficiario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelCreateClt)))
                .addGap(0, 39, Short.MAX_VALUE))
            .addGroup(ConsultarCltLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ConsultarCltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ConsultarCltLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ConsultarCltLayout.createSequentialGroup()
                        .addComponent(jLabelCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        ConsultarCltLayout.setVerticalGroup(
            ConsultarCltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultarCltLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ConsultarCltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ConsultarCltLayout.createSequentialGroup()
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ConsultarCltLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)))
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jRadioButtonBuscarCed)
                .addGap(33, 33, 33)
                .addComponent(jRadioButtonBuscarCuenta)
                .addGap(18, 18, 18)
                .addComponent(jRadioButtonNombre)
                .addGap(30, 30, 30)
                .addComponent(jRadioButtonApellido)
                .addGap(37, 37, 37)
                .addComponent(jLabelBusquedaPor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedTextFieldBuscarPor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(ConsultarCltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCreateClt)
                    .addGroup(ConsultarCltLayout.createSequentialGroup()
                        .addComponent(jLabelCrear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelCreateBeneficiario)))
                .addGap(60, 60, 60)
                .addGroup(ConsultarCltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        VerClt.setBackground(new java.awt.Color(255, 255, 255));
        VerClt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        VerClt.setMaximumSize(new java.awt.Dimension(418, 578));
        VerClt.setMinimumSize(new java.awt.Dimension(418, 578));
        VerClt.setPreferredSize(new java.awt.Dimension(418, 578));
        VerClt.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                VerCltMouseDragged(evt);
            }
        });
        VerClt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                VerCltMousePressed(evt);
            }
        });

        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/flexdesktop/user/Images/atras.png"))); // NOI18N
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Khmer UI", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Datos De Cliente");

        jButton15.setBackground(new java.awt.Color(255, 255, 255));
        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/flexdesktop/user/Images/close2.png"))); // NOI18N
        jButton15.setContentAreaFilled(false);
        jButton15.setFocusable(false);
        jButton15.setOpaque(true);
        jButton15.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/com/flexdesktop/user/Images/close2_roller.png"))); // NOI18N
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jLabel10.setText("Nombre:");

        jLabelName.setBackground(new java.awt.Color(255, 255, 255));
        jLabelName.setFont(new java.awt.Font("Khmer UI", 0, 13)); // NOI18N
        jLabelName.setForeground(new java.awt.Color(102, 102, 102));
        jLabelName.setText("name");

        jLabel12.setText("Apellido:");

        jLabelApellido.setBackground(new java.awt.Color(255, 255, 255));
        jLabelApellido.setFont(new java.awt.Font("Khmer UI", 0, 13)); // NOI18N
        jLabelApellido.setForeground(new java.awt.Color(102, 102, 102));
        jLabelApellido.setText("lastName");

        jLabel14.setText("Cédula:");

        jLabelCedula.setBackground(new java.awt.Color(255, 255, 255));
        jLabelCedula.setFont(new java.awt.Font("Khmer UI", 0, 13)); // NOI18N
        jLabelCedula.setForeground(new java.awt.Color(102, 102, 102));
        jLabelCedula.setText("id");

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/flexdesktop/user/Images/rostro.jpg"))); // NOI18N

        jLabelBorrarClt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/System/Images/Buttons/trashBtt.png"))); // NOI18N
        jLabelBorrarClt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBorrarCltMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelBorrarCltMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBorrarCltMouseExited(evt);
            }
        });

        javax.swing.GroupLayout VerCltLayout = new javax.swing.GroupLayout(VerClt);
        VerClt.setLayout(VerCltLayout);
        VerCltLayout.setHorizontalGroup(
            VerCltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VerCltLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(VerCltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VerCltLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 253, Short.MAX_VALUE)
                        .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VerCltLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(VerCltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(VerCltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(VerCltLayout.createSequentialGroup()
                                    .addComponent(jLabel12)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabelApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(VerCltLayout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabelName, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(VerCltLayout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(VerCltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(VerCltLayout.createSequentialGroup()
                                        .addComponent(jLabelBorrarClt, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(9, 9, 9))
                                    .addComponent(jLabelCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())))
            .addGroup(VerCltLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 242, Short.MAX_VALUE))
        );
        VerCltLayout.setVerticalGroup(
            VerCltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VerCltLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(VerCltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton15))
                .addGap(54, 54, 54)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(VerCltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabelName))
                .addGap(27, 27, 27)
                .addGroup(VerCltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabelApellido))
                .addGap(29, 29, 29)
                .addGroup(VerCltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabelCedula))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                .addGroup(VerCltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VerCltLayout.createSequentialGroup()
                        .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VerCltLayout.createSequentialGroup()
                        .addComponent(jLabelBorrarClt)
                        .addGap(44, 44, 44))))
        );

        registerClt.setBackground(new java.awt.Color(255, 255, 255));
        registerClt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        registerClt.setMaximumSize(new java.awt.Dimension(418, 578));
        registerClt.setMinimumSize(new java.awt.Dimension(418, 578));
        registerClt.setPreferredSize(new java.awt.Dimension(418, 578));
        registerClt.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                registerCltMouseDragged(evt);
            }
        });
        registerClt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                registerCltMousePressed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/flexdesktop/user/Images/hecho.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/flexdesktop/user/Images/atras.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Khmer UI", 0, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Ingresar Datos Del Cliente");

        jLabel7.setFont(new java.awt.Font("Khmer UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Registrar Cliente");

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/flexdesktop/user/Images/close2.png"))); // NOI18N
        jButton3.setContentAreaFilled(false);
        jButton3.setFocusable(false);
        jButton3.setOpaque(true);
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/com/flexdesktop/user/Images/close2_roller.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jFormattedTextFieldEnterName.setCaretColor(new java.awt.Color(204, 204, 204));
        jFormattedTextFieldEnterName.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        jFormattedTextFieldEnterName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldEnterNameActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre:");

        jFormattedTextFieldEnterApellido.setCaretColor(new java.awt.Color(204, 204, 204));
        jFormattedTextFieldEnterApellido.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        jFormattedTextFieldEnterApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldEnterApellidoActionPerformed(evt);
            }
        });

        jLabel4.setText("Apellido:");

        jFormattedTextFieldEnterCedula.setCaretColor(new java.awt.Color(204, 204, 204));
        jFormattedTextFieldEnterCedula.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        jFormattedTextFieldEnterCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldEnterCedulaActionPerformed(evt);
            }
        });

        jLabel5.setText("Cédula:");

        jButton7.setText("Cargar Fotografía");

        jButton8.setText("Agregar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton10.setText("Borrar");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton12.setText("Agregar");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setText("Borrar");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jTable_Dirreciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable_Dirreciones.setCellSelectionEnabled(true);
        jTable_Dirreciones.setFillsViewportHeight(true);
        jTable_Dirreciones.setSurrendersFocusOnKeystroke(true);
        jTable_Dirreciones.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable_DirrecionesKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_Dirreciones);
        jTable_Dirreciones.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        jButton9.setForeground(new java.awt.Color(0, 51, 153));
        jButton9.setText("Print dirreciones");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jTablePhone.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTablePhone.setCellSelectionEnabled(true);
        jTablePhone.setFillsViewportHeight(true);
        jTablePhone.setSurrendersFocusOnKeystroke(true);
        jTablePhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTablePhoneKeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(jTablePhone);

        javax.swing.GroupLayout registerCltLayout = new javax.swing.GroupLayout(registerClt);
        registerClt.setLayout(registerCltLayout);
        registerCltLayout.setHorizontalGroup(
            registerCltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerCltLayout.createSequentialGroup()
                .addGroup(registerCltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registerCltLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 236, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(registerCltLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(registerCltLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(registerCltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(registerCltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(registerCltLayout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(43, 43, 43)
                                    .addComponent(jFormattedTextFieldEnterApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(registerCltLayout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(43, 43, 43)
                                    .addComponent(jFormattedTextFieldEnterName, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(registerCltLayout.createSequentialGroup()
                                    .addComponent(jButton7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton9)))
                            .addGroup(registerCltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(registerCltLayout.createSequentialGroup()
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(registerCltLayout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(43, 43, 43)
                                    .addComponent(jFormattedTextFieldEnterCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(registerCltLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton10)
                        .addGap(18, 18, 18)
                        .addComponent(jButton12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton13)))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(registerCltLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(250, 250, 250)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        registerCltLayout.setVerticalGroup(
            registerCltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerCltLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(registerCltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registerCltLayout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(145, 145, 145))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerCltLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel2)
                        .addGap(48, 48, 48)
                        .addGroup(registerCltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFormattedTextFieldEnterName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(27, 27, 27)))
                .addGroup(registerCltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextFieldEnterApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(30, 30, 30)
                .addGroup(registerCltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextFieldEnterCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(47, 47, 47)
                .addGroup(registerCltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(registerCltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registerCltLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(registerCltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton10)
                            .addComponent(jButton8)))
                    .addGroup(registerCltLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(registerCltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton12)
                            .addComponent(jButton13))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(registerCltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton9))
                .addGap(30, 30, 30)
                .addGroup(registerCltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ConsultarClt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(VerClt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(registerClt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ConsultarClt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(VerClt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(registerClt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        if (validateUI()) {
//            for (int i = 0; i < table.getRowCount(); i++) {// Se crean las rutas por hoja en excel
//                boolean isSelected = (boolean) table.getValueAt(i, 1);
//                if (isSelected) {
//                    String Tabla = table.getValueAt(i, 0).toString();
//                    data.add(Tabla);
//                }
//            }
            dispose();

        } else {
            InfError.showMessage(this, "Debe seleccionar al menos una tabla");
        }


    }//GEN-LAST:event_jButton2ActionPerformed

    private void registerCltMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerCltMouseDragged
        if (!evt.isMetaDown()) {
            Point p = getLocation();
            setLocation(p.x + evt.getX() - point.x, p.y + evt.getY() - point.y);
        }
    }//GEN-LAST:event_registerCltMouseDragged

    private void registerCltMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerCltMousePressed
        if (!evt.isMetaDown()) {
            point.x = evt.getX();
            point.y = evt.getY();
        }
    }//GEN-LAST:event_registerCltMousePressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void ConsultarCltMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConsultarCltMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_ConsultarCltMouseDragged

    private void ConsultarCltMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConsultarCltMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConsultarCltMousePressed

    private void jFormattedTextFieldEnterNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldEnterNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldEnterNameActionPerformed

    private void jFormattedTextFieldEnterApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldEnterApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldEnterApellidoActionPerformed

    private void jFormattedTextFieldEnterCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldEnterCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldEnterCedulaActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        try {
            eliminarFila(jTable_Dirreciones);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        addRow(jTable_Dirreciones);
//        addresList.addElement("Hola");
//        this.jList1.setModel(addresList);
//        jList1.setSelectedIndex(jList1.getLastVisibleIndex());
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        eliminarFila(jTablePhone);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        addRow(jTablePhone);

    }//GEN-LAST:event_jButton12ActionPerformed

    private void jTable_DirrecionesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable_DirrecionesKeyPressed
        int tecla = evt.getKeyCode();
        if (tecla == KeyEvent.VK_F9) {
            //   this.eliminarFila();
        } else {
            // hotKeyPressEvt(evt);
        }
    }//GEN-LAST:event_jTable_DirrecionesKeyPressed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        ArrayList<String> direc = getAddres();
        for (int i = 0; i < direc.size(); i++) {
            System.out.println(direc.get(i));

        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jTablePhoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTablePhoneKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTablePhoneKeyPressed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton15ActionPerformed

    private void VerCltMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VerCltMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_VerCltMouseDragged

    private void VerCltMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VerCltMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_VerCltMousePressed

    private void jRadioButtonBuscarCedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonBuscarCedMouseClicked
        jLabelBusquedaPor.setText("Cédula");
    }//GEN-LAST:event_jRadioButtonBuscarCedMouseClicked

    private void jRadioButtonBuscarCuentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonBuscarCuentaMouseClicked
        jLabelBusquedaPor.setText("Número de Cuenta");
    }//GEN-LAST:event_jRadioButtonBuscarCuentaMouseClicked

    private void jRadioButtonNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonNombreMouseClicked
        jLabelBusquedaPor.setText("Nombre");
    }//GEN-LAST:event_jRadioButtonNombreMouseClicked

    private void jRadioButtonApellidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonApellidoMouseClicked
        jLabelBusquedaPor.setText("Appelido");
    }//GEN-LAST:event_jRadioButtonApellidoMouseClicked

    private void jLabelCreateCltMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCreateCltMouseClicked

        showCustomers sC = new showCustomers(null, true);
        sC.ocultarBotones("VerListado");
        if (jRadioButtonBuscarCed.isSelected()) {
            //To do
            //Obtener los clientes para esa cedulaSeleccionada

            Object cliente[][] = {{jFormattedTextFieldBuscarPor.getText(),
                "Jason", "Salazar"}};
            sC.setData(cliente);
            sC.showDialog();
            String cedulaSeleccionada = sC.getIdSelect();
            setCed(cedulaSeleccionada);
            if (cedulaSeleccionada != "") {
                dispose();
                executeAction();
            }

//****Hacer los mismo para cualquier otra pero cambiar la consulta a resfult
        } else if (jRadioButtonBuscarCuenta.isSelected()) {
            //To do
            //Obtener los clientes para esa cedulaSeleccionada

            Object cliente[][] = {{jFormattedTextFieldBuscarPor.getText(),
                "Jason", "Salazar"}};
            sC.setData(cliente);
            sC.showDialog();
            String cedulaSeleccionada = sC.getIdSelect();
            System.out.println(cedulaSeleccionada);
            if (cedulaSeleccionada != "") {
                dispose();
                executeAction();
            }

        } else if (jRadioButtonNombre.isSelected()) {
            Object cliente[][] = {{jFormattedTextFieldBuscarPor.getText(),
                "Jason", "Salazar"}};
            sC.setData(cliente);
            sC.showDialog();
            String cedulaSeleccionada = sC.getIdSelect();
            System.out.println(cedulaSeleccionada);
            if (cedulaSeleccionada != "") {
                dispose();
                executeAction();
            }
        } else if (jRadioButtonApellido.isSelected()) {
            Object cliente[][] = {{jFormattedTextFieldBuscarPor.getText(),
                "Jason", "Salazar"}};
            sC.setData(cliente);
            sC.showDialog();
            String cedulaSeleccionada = sC.getIdSelect();
            System.out.println(cedulaSeleccionada);
            if (cedulaSeleccionada != "") {
                dispose();
                executeAction();
            }
        }


    }//GEN-LAST:event_jLabelCreateCltMouseClicked

    private void jLabelBorrarCltMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBorrarCltMouseClicked
        String[] options = {"Aceptar", "Cancelar"};
        int selection = JOptionPane.showOptionDialog(this,
                "Desea eliminar el Cliente", "¡Atención!", 0, 0,
                null, options, 0);
        if (selection == 0) {
            //Eliminar
        }
    }//GEN-LAST:event_jLabelBorrarCltMouseClicked

    private void jLabelBorrarCltMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBorrarCltMouseEntered
        jLabelBorrarClt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/System/Images/Buttons/trashBttOvr.png")));

    }//GEN-LAST:event_jLabelBorrarCltMouseEntered

    private void jLabelBorrarCltMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBorrarCltMouseExited
        jLabelBorrarClt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/System/Images/Buttons/trashBtt.png")));
    }//GEN-LAST:event_jLabelBorrarCltMouseExited

    private void jLabelCreateBeneficiarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCreateBeneficiarioMouseClicked
//      jLabelCreateClt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/System/Images/Buttons/addBtt.png")));

    }//GEN-LAST:event_jLabelCreateBeneficiarioMouseClicked

    private void jLabelCreateCltMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCreateCltMouseEntered
        jLabelCreateClt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/System/Images/Buttons/searchBttOvr.png")));
    }//GEN-LAST:event_jLabelCreateCltMouseEntered

    private void jLabelCreateCltMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCreateCltMouseExited
        jLabelCreateClt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/System/Images/Buttons/searchBtt.png")));

    }//GEN-LAST:event_jLabelCreateCltMouseExited

    private void jLabelCreateBeneficiarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCreateBeneficiarioMouseEntered
        jLabelCreateBeneficiario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/System/Images/Buttons/addBttOvr.png")));
    }//GEN-LAST:event_jLabelCreateBeneficiarioMouseEntered

    private void jLabelCreateBeneficiarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCreateBeneficiarioMouseExited
        jLabelCreateBeneficiario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/System/Images/Buttons/addBtt.png")));
    }//GEN-LAST:event_jLabelCreateBeneficiarioMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ConsultarClt;
    private javax.swing.JPanel VerClt;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JFormattedTextField jFormattedTextFieldBuscarPor;
    private javax.swing.JFormattedTextField jFormattedTextFieldEnterApellido;
    private javax.swing.JFormattedTextField jFormattedTextFieldEnterCedula;
    private javax.swing.JFormattedTextField jFormattedTextFieldEnterName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelApellido;
    private javax.swing.JLabel jLabelBorrarClt;
    private javax.swing.JLabel jLabelBusquedaPor;
    private javax.swing.JLabel jLabelCedula;
    private javax.swing.JLabel jLabelCrear;
    private javax.swing.JLabel jLabelCreateBeneficiario;
    private javax.swing.JLabel jLabelCreateClt;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JRadioButton jRadioButtonApellido;
    private javax.swing.JRadioButton jRadioButtonBuscarCed;
    private javax.swing.JRadioButton jRadioButtonBuscarCuenta;
    private javax.swing.JRadioButton jRadioButtonNombre;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTablePhone;
    private javax.swing.JTable jTable_Dirreciones;
    private javax.swing.JPanel registerClt;
    // End of variables declaration//GEN-END:variables

    private void configureTableLook() {
//        DefaultTableCellRenderer centerRender = new DefaultTableCellRenderer();
//        centerRender.setHorizontalAlignment(JLabel.LEFT);
//
//        table.setRowHeight(25);
//        table.getColumnModel().getColumn(0).setPreferredWidth(60);
//
//        table.getColumnModel().getColumn(1).setPreferredWidth(10);
//        table.getColumnModel().getColumn(0).setCellRenderer(centerRender);
//        //  table.getColumnModel().getColumn(1).setCellRenderer(centerRender);
//
//        TableCellRenderer rendererFromHeader = table.getTableHeader().getDefaultRenderer();
//        JLabel headerLabel = (JLabel) rendererFromHeader;
//        headerLabel.setHorizontalAlignment(JLabel.LEFT);
//
//        table.getTableHeader().setFont(new Font("Khmer UI", Font.PLAIN, 14));
//        table.getTableHeader().setForeground(new Color(102, 102, 102));
    }

    private boolean validateUI() {

//        for (int i = 0; i < table.getRowCount() - 1; i++) {
//            boolean parseBoolean = Boolean.parseBoolean(table.getValueAt(i, 1).toString());
//            if (parseBoolean) {
//                return true;
//            }
//        }
        return true;
    }

    private void showPanelOnDialog(javax.swing.JPanel pPanel, javax.swing.JDialog pDialog) {
        pDialog.add(pPanel);
        pPanel.setVisible(true);
        pDialog.setVisible(true);
    }

    private void setVisiblePanel(String panel) {
        removePanels();

        switch (panel) {
            case "RegisterClt":
                add(registerClt);
                registerClt.setVisible(true);
            case "ConsultarClt":

                add(ConsultarClt);
                ConsultarClt.setVisible(true);
            case "VerClt":
                add(VerClt);
                VerClt.setVisible(true);

        }
        if ("CreateBneficiario" == panel) {

            add(ConsultarClt);
            jLabelCreateBeneficiario.setVisible(true);
            jLabelCrear.setVisible(true);
            ConsultarClt.setVisible(true);
        }
    }

    public void removePanels() {
        jLabelCreateBeneficiario.setVisible(false);
        jLabelCrear.setVisible(false);
        registerClt.setVisible(false);
        ConsultarClt.setVisible(false);
        VerClt.setVisible(false);
        remove(registerClt);
        remove(VerClt);
        remove(ConsultarClt);

    }

//    public void completarTablaFacturacion() {
//        //Crea la tabla generica para Facturas
//
//        MyTableModel_FACT model = new MyTableModel_FACT(columnNames, data2, true);
//        this.table1.setModel(
//                model);
////        this.table1.setModel(new Modelo_Facturacion(columnNames, data));
//        //Alinea la primer columna de esta tabla hacia el centro
//        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
//      model.removeRow(1);
//        this.table1.getColumnModel()
//                .getColumn(0).setCellRenderer(centerRenderer);
//    }
    private void eliminarFila(JTable table) {
        try {
            tableModelAddres model = (tableModelAddres) table.getModel();
            int row = table.getSelectedRow();
            ///Si se esta escribiendo en la celda para el editor y luego elimina la
            // fila
            if (!model.data.isEmpty()) {
                if (table.isEditing()) {
                    table.getCellEditor().cancelCellEditing();
                    table.revalidate();
                    table.repaint();
                    table.requestFocus();

                }

                model.removeRow(row);
                table.changeSelection(row - 1, 0, false, false);
                table.revalidate();
                table.repaint();
                table.requestFocus();
            }
            if (model.data.isEmpty()) {
                model.addRow(1);
            }
        } catch (Exception e) {
        }

    }

    private void addRow(JTable table) {
        try {
            tableModelAddres model = (tableModelAddres) table.getModel();

            ///Si se esta escribiendo en la celda para el editor 
            //y luego elimina la fila
            if (!model.data.isEmpty()) {
                if (table.isEditing()) {
                    table.getCellEditor().cancelCellEditing();
                    table.revalidate();
                    table.repaint();
                    table.requestFocus();

                }
            }
            model.addRow(1);
            table.revalidate();
            table.repaint();
            table.requestFocus();
        } catch (Exception e) {
        }

    }

    ArrayList<String> getAddres() {
        ArrayList<String> result = new ArrayList<>();
        for (int i = 0; i < data2.size(); i++) {
            for (int j = 0; j < data2.get(i).length; j++) {
                if (data2.get(i)[j].toString().replace(" ", "") != "") {
                    result.add(data2.get(i)[j].toString());
                }

            }

        }
        return result;
    }

    void setInfoClt(String ced, String name, String lastName) {
        this.jLabelName.setText(name);
        this.jLabelApellido.setText(lastName);
        this.jLabelCedula.setText(ced);

    }

    void setEditableInfoCostumer(String name, String lastName, String ced,
            List<Object[]> direciones) {
        this.jTable_Dirreciones.setModel(new tableModelAddres(direccion,
                direciones, true));
        this.jFormattedTextFieldEnterName.setText(name);
        this.jFormattedTextFieldEnterApellido.setText(lastName);
        this.jFormattedTextFieldEnterCedula.setText(ced);

    }

    void setActionIcon(int action) {

        accion = action;

    }

    void SetTittle(String tittle) {

        jLabel8.setText(tittle);
    }

    private void executeAction() {

        getInformation getInfoPanel = new getInformation(null, true);
        if (accion == Ver) {
            getInfoPanel.SetTittle("Consultar Cliente");
            getInfoPanel.setInVisibleDeleteIcon();
            getInfoPanel.setInfoClt("Cedula", "Nombre", "Apellido");
            getInfoPanel.showDialog("VerClt");
        }
        if (accion == BORRAR) {
            getInfoPanel.SetTittle("Eliminar Cliente");
            getInfoPanel.jLabelBorrarClt.setVisible(true);
            getInfoPanel.setInfoClt("Cedula", "Nombre", "Apellido");
            getInfoPanel.showDialog("VerClt");
        }
        if (accion == Actualizar) {
            getInfoPanel.SetTittle("Actualizar Cliente");
            setInVisibleDeleteIcon();

            //datos de prueba
            String name = "name";
            String lastName = "latsName";
            String ced = "ced";
            List<Object[]> dir = new ArrayList<Object[]>();
            Object dire[] = {"Por ahi"};
            Object dire2[] = {"CuatroFilosDeCuchilloMocho"};
            dir.add(dire);
            dir.add(dire2);
            ////--------------------------------------

            getInfoPanel.setEditableInfoCostumer(name, lastName, ced, dir);
            getInfoPanel.showDialog("RegisterClt");
        }
        if (accion == Beneficiario) {
            //establer id obtenido
            System.out.println("Obtner bediciario");
        }
        if (accion == getIdCliente) {

        }

    }

    void setInVisibleDeleteIcon() {
        jLabelBorrarClt.setVisible(false);

    }

    String getCed() {
        return ced;

    }

    void setCed(String cedNew) {
        ced = cedNew;

    }

}
