/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.flexdesktop.user.GraphicInterface;

import com.flexdesktop.user.Error.InfError;

import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;

import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.Timer;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Melvin
 *
 */
public class showCustomers extends javax.swing.JDialog {

    /**
     * Creates new form EditRoutes
     *
     * @param parent
     * @param modal
     */
    private String[] ColumName  = {"Cedula", "Nombre", "Apellido"};


    Object data2[][] = {{"503890620", "Jason", "Salazar"},
    {"3564874", "Daniel", "Canessa"}, {"2548745", "Edwar", "Umana"},
    {"245784", "Melvin", "Guitierrez"}, {"503890620", "Jason", "Salazar"},
    {"3564874", "Daniel", "Canessa"}, {"2548745", "Edwar", "Umana"},
    {"245784", "Melvin", "Guitierrez"}, {"503890620", "Jason", "Salazar"},
    {"3564874", "Daniel", "Canessa"}, {"2548745", "Edwar", "Umana"},
    {"245784", "Melvin", "Guitierrez"}, {"503890620", "Jason", "Salazar"},
    {"3564874", "Daniel", "Canessa"}, {"2548745", "Edwar", "Umana"},
    {"245784", "Melvin", "Guitierrez"}, {"503890620", "Jason", "Salazar"},
    {"3564874", "Daniel", "Canessa"}, {"2548745", "Edwar", "Umana"}};
    Object paginaAnterior[][] = {{"503890620", "Jason", "Salazar"},
    {"3564874", "Daniel", "Canessa"}, {"2548745", "Edwar", "Umana"},
    {"245784", "Melvin", "Guitierrez"}, {"503890620", "Jason", "Salazar"},
    {"3564874", "Daniel", "Canessa"}, {"2548745", "Edwar", "Umana"},
    {"245784", "Melvin", "Guitierrez"}, {"503890620", "Jason", "Salazar"},
    {"3564874", "Daniel", "Canessa"}, {"2548745", "Edwar", "Umana"},
    {"245784", "Melvin", "Guitierrez"}, {"503890620", "Jason", "Salazar"},
    {"3564874", "Daniel", "Canessa"}, {"2548745", "Edwar", "Umana"},
    {"245784", "Melvin", "Guitierrez"}, {"503890620", "Jason", "Salazar"},
    {"3564874", "Daniel", "Canessa"}, {"2548745", "Edwar", "Umana"}};
    Object pagina2[][] = {{"78749495", "Jose", "Perez"},
    {"3564874", "Juan", "Villegas"}, {"45454", "Andres", "Umana"},
    {"44445757", "Jose", "Lemus"}, {"503890620", "Pepe", "Redriguez"},
    {"3564874", "Sofia", "Vergara"}, {"2548745", "Andreina", "De los Angeles"},
    {"245784", "Saddam", "Husseim"}, {"4545454", "Pedro", "Prado"},
    {"3564874", "Laura", "Chinchilla"}, {"2548745", "Carlos", "Tylor"},
    {"42457857", "Obama", "Barak"}, {"503890620", "Osama", "Bin-Laden"},
    {"7857575", "Leonor", "Aguilar"}, {"7587857544", "Edwar", "Umana"},
    {"7575757", "Luis", "Guillermo"}};
    private int numeroDePaginas = 0;
    private int paginalActual = 1;
    private String idSelect = "";
    private int accionActual=0;
    private int VerListadoClientesFisicos=0;
    private int VerListadoClientesJuridicos=1;
    private ArrayList<String> rowSelect;

    public showCustomers(java.awt.Frame parent, boolean modal) {

        super(parent, modal);
        this.rowSelect = new ArrayList<>();
        initComponents();
        setLocationRelativeTo(parent);

        upDateCostumers();

        //****************
        //setNumeroDePaginas(25);
        initPaginacion();
        //*****************
        
        calculoPaginacion();

    }

    public void showDialog() {

        final Timer timer = new Timer(30, null);
        timer.setRepeats(true);
        timer.addActionListener(new ActionListener() {
            private float opacity = 0;

            @Override
            public void actionPerformed(ActionEvent e) {
                opacity += 0.15f;
                setOpacity(Math.min(opacity, 1));
                if (opacity >= 1) {
                    timer.stop();
                }
            }
        });
        setOpacity(0);
        timer.start();

        //setVisiblePanel(panel);
        setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ListadoClt = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Generica = new javax.swing.JTable();
        TextField_Buscador = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabelModificar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelBorrar = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabelPag3 = new javax.swing.JLabel();
        jLabelPag4 = new javax.swing.JLabel();
        jLabelPag5 = new javax.swing.JLabel();
        jLabelPuntos = new javax.swing.JLabel();
        jLabelUltimoPag = new javax.swing.JLabel();
        jLabelPag2 = new javax.swing.JLabel();
        jLabelPag1 = new javax.swing.JLabel();
        jLabelPuntos1 = new javax.swing.JLabel();
        jLabelSelect = new javax.swing.JLabel();
        jLabelVer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(760, 550));
        setUndecorated(true);

        ListadoClt.setBackground(new java.awt.Color(255, 255, 255));
        ListadoClt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ListadoClt.setMaximumSize(new java.awt.Dimension(700, 500));
        ListadoClt.setMinimumSize(new java.awt.Dimension(700, 500));
        ListadoClt.setPreferredSize(new java.awt.Dimension(700, 500));
        ListadoClt.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                ListadoCltMouseDragged(evt);
            }
        });
        ListadoClt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ListadoCltMousePressed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/flexdesktop/user/Images/atras.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Khmer UI", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Datos De Cliente");

        jLabel8.setFont(new java.awt.Font("Khmer UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Lista de Clientes");

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/flexdesktop/user/Images/close2.png"))); // NOI18N
        jButton6.setContentAreaFilled(false);
        jButton6.setFocusable(false);
        jButton6.setOpaque(true);
        jButton6.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/com/flexdesktop/user/Images/close2_roller.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jTable_Generica.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable_Generica.setGridColor(new java.awt.Color(255, 255, 255));
        jTable_Generica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_GenericaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Generica);

        TextField_Buscador.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TextField_Buscador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_BuscadorActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Buscar:");

        jLabelModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/flexdesktop/Images/Buttons/editBtt.png"))); // NOI18N
        jLabelModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelModificarMouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/flexdesktop/user/Images/back.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });

        jLabelBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/flexdesktop/Images/Buttons/trashBtt.png"))); // NOI18N
        jLabelBorrar.setToolTipText("Borrar factura seleccionada");
        jLabelBorrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelBorrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBorrarMouseClicked(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/flexdesktop/user/Images/next.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
        });

        jLabelPag3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/flexdesktop/user/Images/pagina.png"))); // NOI18N
        jLabelPag3.setText("3");
        jLabelPag3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelPag3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPag3MouseClicked(evt);
            }
        });

        jLabelPag4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/flexdesktop/user/Images/pagina.png"))); // NOI18N
        jLabelPag4.setText("4");
        jLabelPag4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelPag4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPag4MouseClicked(evt);
            }
        });

        jLabelPag5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/flexdesktop/user/Images/pagina.png"))); // NOI18N
        jLabelPag5.setText("5");
        jLabelPag5.setFocusable(false);
        jLabelPag5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelPag5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPag5MouseClicked(evt);
            }
        });

        jLabelPuntos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/flexdesktop/user/Images/PuntosSusp.png"))); // NOI18N

        jLabelUltimoPag.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/flexdesktop/user/Images/pagina.png"))); // NOI18N
        jLabelUltimoPag.setText("6");
        jLabelUltimoPag.setFocusable(false);
        jLabelUltimoPag.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelUltimoPag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelUltimoPagMouseClicked(evt);
            }
        });

        jLabelPag2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/flexdesktop/user/Images/pagina.png"))); // NOI18N
        jLabelPag2.setText("2");
        jLabelPag2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelPag2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPag2MouseClicked(evt);
            }
        });

        jLabelPag1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/flexdesktop/user/Images/paginaSelected.png"))); // NOI18N
        jLabelPag1.setText("1");
        jLabelPag1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelPag1.setOpaque(true);
        jLabelPag1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPag1MouseClicked(evt);
            }
        });

        jLabelPuntos1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelPuntos1.setText("...");

        jLabelSelect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/flexdesktop/Images/Buttons/select.png"))); // NOI18N
        jLabelSelect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSelectMouseClicked(evt);
            }
        });

        jLabelVer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/flexdesktop/Images/Buttons/watchBtt.png"))); // NOI18N
        jLabelVer.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelVer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelVerMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ListadoCltLayout = new javax.swing.GroupLayout(ListadoClt);
        ListadoClt.setLayout(ListadoCltLayout);
        ListadoCltLayout.setHorizontalGroup(
            ListadoCltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListadoCltLayout.createSequentialGroup()
                .addGroup(ListadoCltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(ListadoCltLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ListadoCltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(ListadoCltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(ListadoCltLayout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TextField_Buscador, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ListadoCltLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 718, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(ListadoCltLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(ListadoCltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(ListadoCltLayout.createSequentialGroup()
                                    .addComponent(jLabelModificar)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabelVer)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabelBorrar)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabelSelect)
                                    .addGap(59, 59, 59)
                                    .addComponent(jLabelPag1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabelPuntos1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabelPag2)
                                    .addGap(12, 12, 12)
                                    .addComponent(jLabelPag3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabelPag4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabelPag5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabelPuntos)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabelUltimoPag)
                                    .addGap(45, 45, 45)
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel7))
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        ListadoCltLayout.setVerticalGroup(
            ListadoCltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListadoCltLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ListadoCltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(ListadoCltLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel3))
                    .addGroup(ListadoCltLayout.createSequentialGroup()
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(ListadoCltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextField_Buscador, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(ListadoCltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ListadoCltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ListadoCltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(ListadoCltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPuntos1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(ListadoCltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelPag2)
                                .addComponent(jLabelPag1)))
                        .addComponent(jLabelPag3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelPag4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelPag5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelPuntos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelUltimoPag))
                    .addComponent(jLabelVer)
                    .addComponent(jLabelBorrar)
                    .addComponent(jLabelSelect)
                    .addComponent(jLabelModificar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ListadoClt, javax.swing.GroupLayout.PREFERRED_SIZE, 755, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ListadoClt, javax.swing.GroupLayout.DEFAULT_SIZE, 762, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ListadoCltMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListadoCltMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_ListadoCltMousePressed

    private void ListadoCltMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListadoCltMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_ListadoCltMouseDragged

    private void jLabelBorrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBorrarMouseClicked

        String[] options = {"Aceptar", "Cancelar"};
        int selection = JOptionPane.showOptionDialog(this,
                "Desea eliminar el Cliente", "¡Atención!", 0, 0,
                null, options, 0);
        if (selection == 0) {
            this.eliminar(this.jTable_Generica);
            this.fillTableCostumer();
        }
    }//GEN-LAST:event_jLabelBorrarMouseClicked

    private void jLabelModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelModificarMouseClicked
        //datos de prueba
        String name = "name";
        String lastName = "latsName";
        String ced = "ced";
        List<Object[]> dir = new ArrayList<Object[]>();
        Object dire[] = {"Por ahi"};
        Object dire2[] = {"CuatroFilosDeCuchilloMocho"};
        dir.add(dire);
        dir.add(dire2);
        ////--------------------------------------
        getInformation getInfoPanel = new getInformation(null, true);
        getInfoPanel.setEditableInfoCostumer(name, lastName, ced, dir);
        getInfoPanel.showDialog("RegisterClt");
    }//GEN-LAST:event_jLabelModificarMouseClicked

    private void jLabelVerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelVerMouseClicked

        String ced = jTable_Generica.getValueAt(
                jTable_Generica.getSelectedRow(), 0).toString();

        String name = jTable_Generica.getValueAt(
                jTable_Generica.getSelectedRow(), 1).toString();
        String lastName = jTable_Generica.getValueAt(
                jTable_Generica.getSelectedRow(), 2).toString();

        getInformation getInfoPanel = new getInformation(null, true);
        getInfoPanel.setInfoClt(ced, name, lastName, "CIF", "");
        getInfoPanel.setActionIcon(0);
        getInfoPanel.setInVisibleDeleteIcon();
        getInfoPanel.showDialog("VerClt");
    }//GEN-LAST:event_jLabelVerMouseClicked

    private void TextField_BuscadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_BuscadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_BuscadorActionPerformed

    private void jTable_GenericaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_GenericaMouseClicked
        if (evt.getClickCount() == 2) {
            //            this.jButton_AceptarBusqueda.doClick();
        }
    }//GEN-LAST:event_jTable_GenericaMouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/flexdesktop/user/Images/nextShadow.png")));
    }//GEN-LAST:event_jLabel7MouseEntered

    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().
                getResource("/com/flexdesktop/user/Images/next.png")));

    }//GEN-LAST:event_jLabel7MouseExited

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/flexdesktop/user/Images/backShadow.png")));
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/flexdesktop/user/Images/back.png")));
    }//GEN-LAST:event_jLabel2MouseExited

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked

        JLabel LbAct = getLabelActual();
        JLabel nextLabel = getNextLabel();

        setPaginalActual(Integer.parseInt(getNextLabel().getText()));

        if (getPaginalActual() <= getNumeroDePaginas()) {
            System.out.println("actul " + getPaginalActual() + " ,anter " + LbAct.getText());

            //Si se va para el label5
            if (!nextLabel.isFocusable() && getPaginalActual() < getNumeroDePaginas()) {
                System.out.println("voy pal 5");
                jLabelPag4.setIcon(new javax.swing.ImageIcon(getClass().
                        getResource("/com/flexdesktop/user/Images/paginaSelected.png")));
                jLabelPag4.setOpaque(true);

                draw();

            } else {
                nextLabel.setIcon(new javax.swing.ImageIcon(getClass().
                        getResource("/com/flexdesktop/user/Images/paginaSelected.png")));
                LbAct.setIcon(new javax.swing.ImageIcon(getClass().
                        getResource("/com/flexdesktop/user/Images/pagina.png")));

                nextLabel.setOpaque(true);

                LbAct.setOpaque(false);

            }

            comprobaciones();
            //******
            //Mostrar graficamente la pagina siguiente****************
            String paginaAnterior = LbAct.getText();//Cosultar la siguiente pag
            data2 = pagina2;
            upDateCostumers();

            // System.out.println("El anterior es: " + paginaAnterior);
            //******************************************************
        }
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        JLabel LbAct = getLabelActual();

        JLabel antLabel = getAntLabel();

        if (Integer.parseInt(LbAct.getText()) != 1) {

            if ("1".equals(antLabel.getText()) && jLabelPuntos1.isVisible()) {
                draw2();
                setPaginalActual(paginalActual - 1);
            } else {
                System.out.println("anterior " + antLabel.getText());
                System.out.println("actual " + LbAct.getText());
                setPaginalActual(paginalActual - 1);
                antLabel.setIcon(new javax.swing.ImageIcon(getClass().
                        getResource("/com/flexdesktop/user/Images/paginaSelected.png")));
                antLabel.setOpaque(true);
                LbAct.setIcon(new javax.swing.ImageIcon(getClass().
                        getResource("/com/flexdesktop/user/Images/pagina.png")));
                LbAct.setOpaque(false);

            }
        }

        comprobaciones();
        //System.out.println("actual pa : " + paginalActual);
        //Mostrar graficamente la pagina siguiente****************
//        String paginaAnterior = LbAct.getText();//Cosultar la siguiente pag
//        System.out.println("El actual es: " + paginaAnterior);
        //******************************************************

        //**ConsultarResfult
        data2 = paginaAnterior;
        upDateCostumers();
        //////*****
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabelPag1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPag1MouseClicked
        jLabelUltimoPag.setText("" + getNumeroDePaginas());
        jLabelPag5.setText("5");
        jLabelPag4.setText("4");
        jLabelPag3.setText("3");
        jLabelPag2.setText("2");
        setFocusPanel(jLabelPag1);
        comprobaciones();


    }//GEN-LAST:event_jLabelPag1MouseClicked

    private void jLabelPag2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPag2MouseClicked
        setFocusPanel(jLabelPag2);
    }//GEN-LAST:event_jLabelPag2MouseClicked

    private void jLabelPag3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPag3MouseClicked
        setFocusPanel(jLabelPag3);
    }//GEN-LAST:event_jLabelPag3MouseClicked

    private void jLabelPag4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPag4MouseClicked
        setFocusPanel(jLabelPag4);
    }//GEN-LAST:event_jLabelPag4MouseClicked

    private void jLabelPag5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPag5MouseClicked
        setFocusPanel(jLabelPag5);
    }//GEN-LAST:event_jLabelPag5MouseClicked

    private void jLabelUltimoPagMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelUltimoPagMouseClicked
        jLabelPag5.setText(jLabelUltimoPag.getText());
        jLabelPag4.setText("" + (Integer.parseInt(jLabelUltimoPag.getText()) - 1));
        jLabelPag3.setText("" + (Integer.parseInt(jLabelUltimoPag.getText()) - 2));
        jLabelPag2.setText("" + (Integer.parseInt(jLabelUltimoPag.getText()) - 3));
        setFocusPanel(jLabelPag5);
        comprobaciones();
    }//GEN-LAST:event_jLabelUltimoPagMouseClicked

    private void jLabelSelectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSelectMouseClicked
        setIdSelect(jTable_Generica.getValueAt(
                jTable_Generica.getSelectedRow(), 0).toString());
        setRowSelect();
        dispose();
    }//GEN-LAST:event_jLabelSelectMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ListadoClt;
    private javax.swing.JTextField TextField_Buscador;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelBorrar;
    private javax.swing.JLabel jLabelModificar;
    private javax.swing.JLabel jLabelPag1;
    private javax.swing.JLabel jLabelPag2;
    private javax.swing.JLabel jLabelPag3;
    private javax.swing.JLabel jLabelPag4;
    private javax.swing.JLabel jLabelPag5;
    private javax.swing.JLabel jLabelPuntos;
    private javax.swing.JLabel jLabelPuntos1;
    private javax.swing.JLabel jLabelSelect;
    private javax.swing.JLabel jLabelUltimoPag;
    private javax.swing.JLabel jLabelVer;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Generica;
    // End of variables declaration//GEN-END:variables

    private boolean validateUI() {

//        for (int i = 0; i < table.getRowCount() - 1; i++) {
//            boolean parseBoolean = Boolean.parseBoolean(table.getValueAt(i, 1).toString());
//            if (parseBoolean) {
//                return true;
//            }
//        }
        return true;
    }

    private void showPanelOnDialog(javax.swing.JPanel pPanel, javax.swing.JDialog pDialog) {
        pDialog.add(pPanel);
        pPanel.setVisible(true);
        pDialog.setVisible(true);
    }

    public void upDateCostumers() {
//        AdminBD.consultarClientes();
//        data = AdminBD.getData();
//        String[] columnNames = AdminBD.getColumnNames();

        this.jTable_Generica.setModel(new tableModelGeneric(ColumName, data2));
        //Crea el ordenador para la tabla generica
        TableRowSorter<TableModel> ordenador = new TableRowSorter<TableModel>(this.jTable_Generica.getModel());
        this.jTable_Generica.setRowSorter(ordenador);
        Vector<RowSorter.SortKey> qq = new Vector<RowSorter.SortKey>();
        qq.add(new RowSorter.SortKey(0, SortOrder.ASCENDING));
        ordenador.setSortKeys(qq);
        jTable_Generica.requestFocus();
        jTable_Generica.changeSelection(0, 0, false, false);
        /**
         * Agrega el listener al JtextField del buscador *
         */
        this.TextField_Buscador.getDocument().addDocumentListener(new ListenerBuscador(this.TextField_Buscador, ordenador));

    }

    private void eliminar(JTable table) {

        int row = table.getSelectedRow();
        if (row < 0) {

            JOptionPane.showMessageDialog(
                    null,
                    "No ha selecionado un cliente",
                    "Alert!", JOptionPane.ERROR_MESSAGE);
            return;

        }
        String cedula = table.getValueAt(row, 0).toString();

        //Eliminar el cliente con la cedula 'cedula'
    }

    public void fillTableCostumer() {

        //Realiza la consulta para obtener las los clientes a mostrar
        /**
         * **
         *///
        this.jTable_Generica.setModel(new tableModelGeneric(ColumName, data2));
        //Alinea la primer columna de esta tabla hacia el centro
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();

        this.jTable_Generica.getColumnModel().getColumn(0).
                setCellRenderer(centerRenderer);
    }

    /**
     * Permite mostrar graficamente el numero de paginas que hay
     */
    private void initPaginacion() {

        this.jLabelPuntos1.setVisible(false);
        if (numeroDePaginas >= 6) {
            jLabelUltimoPag.setText("" + numeroDePaginas);
        } else {
            ocultarPaginas();
            if (numeroDePaginas >= 1) {
                this.jLabelPag1.setVisible(true);
                if (numeroDePaginas >= 2) {
                    this.jLabelPag2.setVisible(true);
                    if (numeroDePaginas >= 3) {
                        this.jLabelPag3.setVisible(true);

                        if (numeroDePaginas >= 4) {
                            this.jLabelPag4.setVisible(true);

                            if (numeroDePaginas >= 5) {
                                this.jLabelPag5.setVisible(true);

                            }

                        }

                    }

                }
            }

        }

    }

    private void ocultarPaginas() {

        this.jLabelPag1.setVisible(false);
        this.jLabelPag2.setVisible(false);
        this.jLabelPag3.setVisible(false);
        this.jLabelPag4.setVisible(false);
        this.jLabelPag5.setVisible(false);
        this.jLabelUltimoPag.setVisible(false);
        this.jLabelPuntos.setVisible(false);

    }

    /**
     * @return the numeroDePaginas
     */
    public int getNumeroDePaginas() {
        return numeroDePaginas;
    }

    /**
     * @param numeroDePaginas the numeroDePaginas to set
     */
    public void setNumeroDePaginas(int numeroDePaginas) {
        this.numeroDePaginas = numeroDePaginas;
    }

    /**
     * @return the paginalActual
     */
    public int getPaginalActual() {
        return paginalActual;
    }

    /**
     * @param paginalActual the paginalActual to set
     */
    public void setPaginalActual(int paginalActual) {
        this.paginalActual = paginalActual;
    }

    public JLabel getLabelActual() {
        if (jLabelPag1.isOpaque()) {
            return jLabelPag1;
        } else if (jLabelPag2.isOpaque()) {
            return jLabelPag2;
        } else if (jLabelPag3.isOpaque()) {
            return jLabelPag3;
        } else if (jLabelPag4.isOpaque()) {
            return jLabelPag4;
        } else if (jLabelPag5.isOpaque()) {
            return jLabelPag5;
        }

        return jLabelUltimoPag;

    }

    public JLabel getNextLabel() {
        if (jLabelPag1.isOpaque()) {
            return jLabelPag2;
        } else if (jLabelPag2.isOpaque()) {
            return jLabelPag3;
        } else if (jLabelPag3.isOpaque()) {
            return jLabelPag4;
        } else if (jLabelPag4.isOpaque()) {
            return jLabelPag5;
        } else if (jLabelPag5.isOpaque()) {
            return jLabelUltimoPag;
        }

        return jLabelUltimoPag;

    }

    public JLabel getAntLabel() {
        if (jLabelPag1.isOpaque()) {
            return jLabelPag1;
        } else if (jLabelPag2.isOpaque()) {
            return jLabelPag1;
        } else if (jLabelPag3.isOpaque()) {
            return jLabelPag2;
        } else if (jLabelPag4.isOpaque()) {
            return jLabelPag3;
        } else if (jLabelPag5.isOpaque()) {
            return jLabelPag4;
        }

        return jLabelPag5;

    }

    private void draw() {
        jLabelPag4.setText("" + paginalActual);
        jLabelPag3.setText("" + (paginalActual - 1));
        jLabelPag2.setText("" + (paginalActual - 2));
        jLabelPag5.setText("" + (paginalActual + 1));

    }

    private void draw2() {
        jLabelPag2.setText("" + (paginalActual - 1));
        jLabelPag3.setText("" + (paginalActual));
        jLabelPag4.setText("" + (paginalActual + 1));
        jLabelPag5.setText("" + (paginalActual + 2));

    }

    private void comprobaciones() {
        ///***comprobar si necesita puntos suspen al inicio
        if (Integer.parseInt(jLabelPag2.getText()) > 2) {
            jLabelPuntos1.setVisible(true);
        }
        if (Integer.parseInt(jLabelPag2.getText()) == 2) {
            jLabelPuntos1.setVisible(false);
        }
        //***********

        ///***comprobar si necesita puntos suspen al final
        if (Integer.parseInt(jLabelPag5.getText()) >= getNumeroDePaginas()) {

            jLabelPuntos.setVisible(false);
            jLabelUltimoPag.setVisible(false);
        }
        if (Integer.parseInt(jLabelPag5.getText()) < getNumeroDePaginas()) {
            jLabelPuntos.setVisible(true);
            jLabelUltimoPag.setVisible(true);
        }

    }

    void setFocusPanel(JLabel label) {
        JLabel LbAct = getLabelActual();

        label.setIcon(new javax.swing.ImageIcon(getClass().
                getResource("/com/flexdesktop/user/Images/paginaSelected.png")));
        label.setOpaque(true);
        LbAct.setIcon(new javax.swing.ImageIcon(getClass().
                getResource("/com/flexdesktop/user/Images/pagina.png")));
        LbAct.setOpaque(false);
        setPaginalActual(Integer.parseInt(label.getText()));

    }

    void setData(Object[][] dataNew) {
        data2 = dataNew;
        upDateCostumers();
    }

    void ocultarBotones(String caso) {

        if ("VerListadoAcciones".equals(caso)) {
            this.jLabelSelect.setVisible(false);
            this.jLabelModificar.setVisible(true);
            this.jLabelVer.setVisible(true);
            this.jLabelBorrar.setVisible(true);

        }
        if ("VerListado".equals(caso)) {
            this.jLabelSelect.setVisible(true);
            this.jLabelModificar.setVisible(false);
            this.jLabelVer.setVisible(false);
            this.jLabelBorrar.setVisible(false);

        }
        if ("VerCierres".equals(caso)) {
            this.jLabelSelect.setVisible(false);
            this.jLabelModificar.setVisible(false);
            this.jLabelVer.setVisible(false);
            this.jLabelBorrar.setVisible(false);
            this.jLabel3.setVisible(false);
            this.jLabel8.setText("Lista de Cierres");
        }

    }

    /**
     * @return the idSelect
     */
    public String getIdSelect() {
        return idSelect;
    }

    /**
     * @param idSelect the idSelect to set
     */
    public void setIdSelect(String idSelect) {
        this.idSelect = idSelect;
    }

    /**
     * @param ColumName the ColumName to set
     */
    public void setColumName(String[] ColumName) {
        this.ColumName = ColumName;
    }

    private void setRowSelect() {
        for (int i = 0; i < jTable_Generica.getColumnCount(); i++) {
            rowSelect.add(jTable_Generica.getValueAt(
                    jTable_Generica.getSelectedRow(), i).toString());
        }

    }

    ArrayList<String> getRowSelect() {
        return rowSelect;

    }

    /**
     * @return the accionActual
     */
    public int getAccionActual() {
        return accionActual;
    }

    /**
     * @param accionActual the accionActual to set
     */
    public void setAccionActual(int accionActual) {
        this.accionActual = accionActual;
    }

    private void calculoPaginacion() {
    
    //calcular numero paginas
    
    
    }
}
